cask "difforbit" do
  version "0.1.0"
  sha256 "321c722917daf74e87f20228ddd2ff2723c6204774def9a16522f58af4958386"

  # Updated URL to use the universal DMG name generated by the new workflow
  url "https://github.com/Pratik948/difforbit/releases/download/v#{version}/DiffOrbit_#{version}_universal.dmg"
  
  name "DiffOrbit"
  desc "AI-powered PR code review desktop app for macOS"
  homepage "https://github.com/Pratik948/difforbit"

  app "DiffOrbit.app"

  # Clear the quarantine attribute — required because DiffOrbit is not
  # notarised with an Apple certificate.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{appdir}/DiffOrbit.app"],
                   sudo: false
  end

  uninstall quit: "com.difforbit.app"

  zap trash: [
    "~/Library/Application Support/DiffOrbit",
    "~/Library/Logs/DiffOrbit",
    "~/Library/LaunchAgents/com.difforbit.app.plist",
    "~/Library/Preferences/com.difforbit.app.plist",
    "~/Library/Saved Application State/com.difforbit.app.savedState",
  ]
end